sudo: required
language: android
jdk: oraclejdk8
compiler: gcc

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25  
    - extra-android-support
    - extra-android-m2repository
    - ${ANDROID_TARGET}
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}    
    
licenses:
    - '.+'

before_install:
    - sudo apt-get update
    - chmod +x app/src/test/res/install_opencv.sh
    - chmod +x app/src/test/res/launch_emulator.sh

install:
    - sudo apt-get install python-numpy
  
before_script:
    - app/src/test/res/install_opencv.sh

script:
    - app/src/test/res/launch_emulator.sh
    
after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle